# https://github.com/golangci/golangci-lint-action#how-to-use
name: lint
on:
  - push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26.4' # renovate: datasource=golang-version depName=go
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          install-mode: goinstall
          version: v2.12.2 # renovate: datasource=github-tags depName=golangci/golangci-lint
          args: --timeout 5m0s
